SELECT X.SALES_DATE, X.PRODUCT_ID, X.USER_ID, X.SALES_AMOUNT
FROM
(
SELECT DATE_FORMAT(SALES_DATE,'%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, IFNULL(USER_ID, NULL) AS USER_ID, SALES_AMOUNT
FROM ONLINE_SALE 
WHERE DATE_FORMAT(SALES_DATE,'%Y-%m') = '2022-03'
UNION
SELECT DATE_FORMAT(SALES_DATE,'%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
FROM OFFLINE_SALE 
WHERE DATE_FORMAT(SALES_DATE,'%Y-%m') = '2022-03'
) X
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID