SELECT A.CAR_ID, A.CAR_TYPE, ROUND(30 * A.DAILY_FEE * (1-C.DISCOUNT_RATE/100),0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR A
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C ON A.CAR_TYPE = C.CAR_TYPE AND DURATION_TYPE = '30일 이상'
WHERE A.CAR_TYPE IN ('세단','SUV')
 AND A.CAR_ID NOT IN(SELECT H.CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H WHERE DATE_FORMAT(H.START_DATE,'%Y-%m-%d') <='2022-11-31' AND DATE_FORMAT(H.END_DATE,'%Y-%m-%d') >='2022-11-01') 
 AND ROUND(30 * A.DAILY_FEE * (1-C.DISCOUNT_RATE/100),0)  BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC