SELECT HISTORY_ID, 
    CASE
    WHEN RENTAL_DATE < 7 THEN ROUND(DAILY_FEE * RENTAL_DATE, 0) 
        ELSE ROUND(DAILY_FEE  *(1 - DISCOUNT_RATE/100) * RENTAL_DATE, 0)
        END AS FEE
FROM (
    SELECT CAR_ID, HISTORY_ID, DATEDIFF(END_DATE, START_DATE) +1 AS RENTAL_DATE,
    CASE 
        WHEN DATEDIFF(END_DATE, START_DATE) +1 BETWEEN 7 AND 29 THEN '7일 이상'
        WHEN DATEDIFF(END_DATE, START_DATE) +1 BETWEEN 30 AND 89 THEN '30일 이상'
        WHEN DATEDIFF(END_DATE, START_DATE) +1 >= 90 THEN '90일 이상'
    END AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
) AS HR
LEFT JOIN CAR_RENTAL_COMPANY_CAR CAR ON HR.CAR_ID = CAR.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON P.CAR_TYPE = CAR.CAR_TYPE AND HR.DURATION_TYPE = P.DURATION_TYPE
WHERE CAR.CAR_TYPE = '트럭'
GROUP BY HR.HISTORY_ID
ORDER BY FEE DESC, HISTORY_ID DESC