SELECT AP.APNT_NO, PT.PT_NAME, PT.PT_NO, AP.MCDP_CD, DR.DR_NAME, AP.APNT_YMD
FROM APPOINTMENT AP
JOIN PATIENT PT ON AP.PT_NO = PT.PT_NO
JOIN DOCTOR DR ON AP.MDDR_ID = DR.DR_ID
WHERE AP.APNT_CNCL_YN = 'N'
AND DATE_FORMAT(AP.APNT_YMD,'%Y-%m-%d') ='2022-04-13' 
ORDER BY AP.APNT_YMD