WITH RECURSIVE CTE AS(
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR +1 FROM CTE
    WHERE HOUR < 23
)

SELECT CTE.HOUR, COUNT(B.DATETIME) AS COUNT
FROM CTE
LEFT JOIN ANIMAL_OUTS B ON CTE.HOUR = HOUR(B.DATETIME) 
GROUP BY CTE.HOUR
ORDER BY CTE.HOUR