SELECT A.MEMBER_NAME, B.REVIEW_TEXT, DATE_FORMAT(B.REVIEW_DATE,'%Y-%m-%d')
FROM MEMBER_PROFILE A
JOIN REST_REVIEW B ON A.MEMBER_ID = B.MEMBER_ID
JOIN (
SELECT MEMBER_ID, COUNT(REVIEW_ID) AS CNT
FROM REST_REVIEW
GROUP BY MEMBER_ID
) X ON A.MEMBER_ID = X.MEMBER_ID
WHERE X.CNT = (SELECT MAX(CNT) FROM (SELECT COUNT(*) AS CNT FROM REST_REVIEW GROUP BY MEMBER_ID) AS W)
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC