SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM (
    SELECT CATEGORY, PRICE, PRODUCT_NAME, RANK() OVER (PARTITION BY CATEGORY ORDER BY PRICE DESC) AS RN
    FROM FOOD_PRODUCT 
    ) AS X
WHERE X.RN = 1
AND X.CATEGORY IN('과자', '국', '김치', '식용유')
ORDER BY PRICE DESC